name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'blog/articles/md/**'
      - 'blog/scripts/**'
      - 'blog/package.json'
  pull_request:
    paths:
      - 'blog/articles/md/**'
      - 'blog/scripts/**'
      - 'blog/package.json'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd blog
          npm install
          
      - name: Convert Markdown to HTML
        run: |
          cd blog
          npm run build
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add blog/articles/*.html blog/articles.json blog/.nojekyll
          git commit -m "Update HTML files and articles.json" || exit 0
          git push

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true 