name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd blog
          npm install

      - name: Build
        run: |
          cd blog
          node scripts/convert_md_to_html.js

      - name: Deploy
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: blog/articles/html  # デプロイするディレクトリ
          branch: main  # mainブランチにデプロイ 